eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8000/eureka
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
  instance:
    hostname: localhost
    
server:
  port: 8001

spring:
  application:
    name: user-service