eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8000/eureka
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    hostname: ${EUREKA_INSTANCE_HOST}
    
server:
  port: 8001

spring:
  application:
    name: user-service